"""add_district_to_users

Revision ID: 50a397394085
Revises: 4638f7ca9728
Create Date: 2026-06-20 04:07:42.065095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a397394085'
down_revision: Union[str, None] = '4638f7ca9728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('district', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'district')
    # ### end Alembic commands ###
